---

# localHookDir: ./hooks
# doNotAutoAddHooksFromLocalHookDir: false
hooks:
  - hookName: commit-msg
    files:
      - path: ./hooks/CommitMustContainValidTags.js
        extraArguments:
          - name: FilePath
            value: ./hooks/CommitMessageTags.json
      - path: ./hooks/yet-another-commit-msg
        extraArguments:
          - name: Name1
            value: Value1
          - name: Name2
            value: Value2