---

# localHookDir: ./hooks
# autoAddHooks: ByFileName
hooks:
  - hookName: commit-msg
    files:
      - path: https://example.123faketld/some_file.go
        extraArguments:
          - name: FilePath
            value: ./hooks/CommitMessageTags.json