codecov:
  require_ci_to_pass: yes

comment: false

coverage:
  status:
    project:
      default:
        target: 60%
    patch:
      default:
        target: 40%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "main.go"
  - "source/boundary"
