codecov:
  require_ci_to_pass: yes

comment: false

coverage:
  precision: 2
  round: down
  range: "60...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "main.go"
  - "source/boundary"
