#!/usr/bin/env node

const fs = require('fs');

console.log("Hello from the Hooks folder!");

// The first element of process.argv is the execution path,
// and the second is the path for the js file. If you want
// to access the params related to git hooks, they will start at 
// index 2!
const pathToCommitMessage = process.argv[2];
console.log(`Commit Message can be found at '${pathToCommitMessage}'.`);
console.log('The commit message is as follows:');
// Encoding has to be specified, otherwise weirdness will occur
const message = fs.readFileSync(pathToCommitMessage, {encoding: "utf-8"});
console.log(message);
console.log('--------------End--------------');